<a href="https://colab.research.google.com/github/SuyashPant04/Spam-Classifier/blob/main/SpamClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [5]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Spam/spam.csv', encoding='latin1')

In [6]:
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [8]:
data = data.drop(columns = data.columns[-3:])

In [9]:
data

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [10]:

import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_rus.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/book_grammars.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/city_database.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dolch.zip.
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/english_wordnet.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/europarl_raw.zip.
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v15.zip.
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v17.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ieer.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/indian.zip.
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/kimmo.zip.
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/large_grammars.zip.
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/lin_thesaurus.zip.
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mac_morpho.zip.
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker_tab.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/maxent_treebank_pos_tagger_tab.zip.
[nltk_data]    | Downloading package mock_corpus to /root/nltk_data...
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/moses_sample.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mte_teip5.zip.
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Unzipping misc/mwa_ppdb.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nonbreaking_prefixes.zip.
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nps_chat.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/opinion_lexicon.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/paradigms.zip.
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pe08.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping misc/perluniprops.zip.
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pil.zip.
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pl196x.zip.
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/porter_test.zip.
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ppattach.zip.
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/problem_reports.zip.
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_1.zip.
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_2.zip.
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pros_cons.zip.
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ptb.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package punkt_tab to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt_tab.zip.
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/qc.zip.
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/rslp.zip.
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/rte.zip.
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/sample_grammars.zip.
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/senseval.zip.
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentence_polarity.zip.
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentiwordnet.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/smultron.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/spanish_grammars.zip.
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/state_union.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/subjectivity.zip.
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/swadesh.zip.
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/switchboard.zip.
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets.zip.
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets_json.zip.
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/timit.zip.
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/toolbox.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr.zip.
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/unicode_samples.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/universal_tagset.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet3.zip.
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/webtext.zip.
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Unzipping models/wmt15_eval.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/word2vec_sample.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet2022.zip.
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all

True

In [11]:
data = data.rename(columns = {'v1': 'Label', 'v2': 'Text'})

In [12]:
data['Text'].dropna(inplace=True)

In [13]:
data

     Label                                               Text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [14]:
# Converting all entries in 'text' to lowercase in case they are not
data['Text'] = [entry.lower() for entry in data['Text']]

In [15]:
from sklearn.preprocessing import LabelEncoder
from nltk.tokenize import word_tokenize

In [16]:
data['Text']= [word_tokenize(entry) for entry in data['Text']]

In [17]:
data.head()

  Label                                               Text
0   ham  [go, until, jurong, point, ,, crazy, .., avail...
1   ham           [ok, lar, ..., joking, wif, u, oni, ...]
2  spam  [free, entry, in, 2, a, wkly, comp, to, win, f...
3   ham  [u, dun, say, so, early, hor, ..., u, c, alrea...
4   ham  [nah, i, do, n't, think, he, goes, to, usf, ,,...

In [18]:
from nltk.stem import WordNetLemmatizer
from collections import defaultdict
from nltk.corpus import wordnet as wn
from nltk.corpus import stopwords
from nltk import pos_tag

In [19]:
tag_map = defaultdict(lambda : wn.NOUN)
tag_map['J'] = wn.ADJ
tag_map['V'] = wn.VERB
tag_map['R'] = wn.ADV
word_Lemmatizer = WordNetLemmatizer()

In [20]:
print(tag_map)
data['Text']

defaultdict(<function <lambda> at 0x7c2580b67ce0>, {'J': 'a', 'V': 'v', 'R': 'r'})

0       [go, until, jurong, point, ,, crazy, .., avail...
1                [ok, lar, ..., joking, wif, u, oni, ...]
2       [free, entry, in, 2, a, wkly, comp, to, win, f...
3       [u, dun, say, so, early, hor, ..., u, c, alrea...
4       [nah, i, do, n't, think, he, goes, to, usf, ,,...
                              ...
5567    [this, is, the, 2nd, time, we, have, tried, 2,...
5568     [will, ì_, b, going, to, esplanade, fr, home, ?]
5569    [pity, ,, *, was, in, mood, for, that, ., so, ...
5570    [the, guy, did, some, bitching, but, i, acted,...
5571                  [rofl, ., its, true, to, its, name]
Name: Text, Length: 5572, dtype: object

In [21]:
for index, entry in enumerate(data['Text']):
    Final_words = []
    for word, tag in pos_tag(entry):
        if word not in stopwords.words('english') and word.isalpha():
            word_Final = word_Lemmatizer.lemmatize(word,pos = tag_map[tag[0]])
            Final_words.append(word_Final)
    data.loc[index,'final'] = str(Final_words)

In [22]:
data

,Label,Text,final
0,ham,"[go, until, jurong, point, ,, crazy, .., avail...","['go', 'jurong', 'point', 'crazy', 'available'..."
1,ham,"[ok, lar, ..., joking, wif, u, oni, ...]","['ok', 'lar', 'joke', 'wif', 'u', 'oni']"
2,spam,"[free, entry, in, 2, a, wkly, comp, to, win, f...","['free', 'entry', 'wkly', 'comp', 'win', 'fa',..."
3,ham,"[u, dun, say, so, early, hor, ..., u, c, alrea...","['u', 'dun', 'say', 'early', 'hor', 'u', 'c', ..."
4,ham,"[nah, i, do, n't, think, he, goes, to, usf, ,,...","['nah', 'think', 'go', 'usf', 'live', 'around'..."
...,...,...,...
5567,spam,"[this, is, the, 2nd, time, we, have, tried, 2,...","['time', 'try', 'contact', 'u', 'pound', 'priz..."
5568,ham,"[will, ì_, b, going, to, esplanade, fr, home, ?]","['b', 'go', 'esplanade', 'fr', 'home']"
5569,ham,"[pity, ,, *, was, in, mood, for, that, ., so, ...","['pity', 'mood', 'suggestion']"
5570,ham,"[the, guy, did, some, bitching, but, i, acted,...","['guy', 'bitching', 'act', 'like', 'interested..."
5571,ham,"[rofl, ., its, true, to, its, name]","['rofl', 'true', 'name']"

In [27]:
from sklearn.model_selection import train_test_split

Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(data['final'],data['Label'],test_size=0.15)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score

**Data Encoding(TFIDF)**

In [29]:
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

In [30]:
Tfidf_vect = TfidfVectorizer(max_features=3000)
Tfidf_vect.fit(data['final'])

TfidfVectorizer(max_features=3000)

In [31]:
Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

**Data Encoding(Count Vectorizer)**

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
vectorizer = CountVectorizer(max_features=5000)

vectorizer.fit(data['final'])

CountVectorizer(max_features=5000)

In [34]:
# Printing the identified Unique words along with their indices
print("Vocabulary: ", vectorizer.vocabulary_)

Vocabulary:  {'go': np.int64(1577), 'jurong': np.int64(2219), 'point': np.int64(3430), 'crazy': np.int64(609), 'available': np.int64(203), 'bugis': np.int64(382), 'great': np.int64(1641), 'world': np.int64(4925), 'la': np.int64(2315), 'buffet': np.int64(381), 'cine': np.int64(499), 'get': np.int64(1541), 'wat': np.int64(4834), 'ok': np.int64(3109), 'lar': np.int64(2343), 'joke': np.int64(2191), 'wif': np.int64(4882), 'oni': np.int64(3133), 'free': np.int64(1420), 'entry': np.int64(1094), 'wkly': np.int64(4908), 'comp': np.int64(546), 'win': np.int64(4889), 'fa': np.int64(1210), 'cup': np.int64(632), 'final': np.int64(1300), 'tkts': np.int64(4626), 'may': np.int64(2650), 'text': np.int64(4564), 'receive': np.int64(3742), 'question': np.int64(3655), 'std': np.int64(4420), 'txt': np.int64(4705), 'rate': np.int64(3699), 'apply': np.int64(151), 'dun': np.int64(974), 'say': np.int64(4000), 'early': np.int64(990), 'hor': np.int64(1870), 'already': np.int64(102), 'nah': np.int64(2892), 'think': np.int64(4585), 'usf': np.int64(4763), 'live': np.int64(2447), 'around': np.int64(173), 'though': np.int64(4593), 'freemsg': np.int64(1426), 'hey': np.int64(1806), 'darling': np.int64(679), 'week': np.int64(4852), 'word': np.int64(4921), 'back': np.int64(217), 'like': np.int64(2416), 'fun': np.int64(1475), 'still': np.int64(4427), 'tb': np.int64(4535), 'xxx': np.int64(4951), 'send': np.int64(4070), 'rcv': np.int64(3709), 'even': np.int64(1136), 'brother': np.int64(368), 'speak': np.int64(4378), 'treat': np.int64(4678), 'aid': np.int64(76), 'patent': np.int64(3283), 'per': np.int64(3315), 'request': np.int64(3822), 'melle': np.int64(2682), 'oru': np.int64(3180), 'minnaminunginte': np.int64(2734), 'nurungu': np.int64(3056), 'vettam': np.int64(4782), 'set': np.int64(4091), 'callertune': np.int64(415), 'caller': np.int64(414), 'press': np.int64(3533), 'copy': np.int64(584), 'friend': np.int64(1440), 'winner': np.int64(4893), 'value': np.int64(4773), 'network': np.int64(2955), 'customer': np.int64(644), 'select': np.int64(4057), 'receivea': np.int64(3743), 'prize': np.int64(3562), 'reward': np.int64(3864), 'claim': np.int64(503), 'call': np.int64(410), 'code': np.int64(529), 'valid': np.int64(4771), 'hour': np.int64(1882), 'mobile': np.int64(2780), 'month': np.int64(2807), 'entitle': np.int64(1091), 'update': np.int64(4744), 'late': np.int64(2350), 'colour': np.int64(538), 'camera': np.int64(421), 'co': np.int64(524), 'gon': np.int64(1590), 'na': np.int64(2887), 'home': np.int64(1850), 'soon': np.int64(4343), 'want': np.int64(4827), 'talk': np.int64(4523), 'stuff': np.int64(4449), 'anymore': np.int64(134), 'tonight': np.int64(4649), 'cry': np.int64(620), 'enough': np.int64(1082), 'today': np.int64(4635), 'six': np.int64(4231), 'chance': np.int64(465), 'cash': np.int64(444), 'pound': np.int64(3482), 'cost': np.int64(589), 'tsandcs': np.int64(4689), 'reply': np.int64(3817), 'hl': np.int64(1825), 'info': np.int64(2027), 'urgent': np.int64(4752), 'membership': np.int64(2687), 'jackpot': np.int64(2129), 'lccltd': np.int64(2366), 'pobox': np.int64(3422), 'search': np.int64(4037), 'right': np.int64(3875), 'thank': np.int64(4572), 'promise': np.int64(3588), 'wont': np.int64(4919), 'take': np.int64(4520), 'help': np.int64(1791), 'grant': np.int64(1630), 'fulfil': np.int64(1472), 'wonderful': np.int64(4917), 'blessing': np.int64(304), 'time': np.int64(4616), 'date': np.int64(685), 'sunday': np.int64(4477), 'use': np.int64(4760), 'credit': np.int64(612), 'click': np.int64(513), 'wap': np.int64(4828), 'link': np.int64(2432), 'next': np.int64(2967), 'message': np.int64(2702), 'http': np.int64(1901), 'oh': np.int64(3104), 'watch': np.int64(4835), 'eh': np.int64(1027), 'remember': np.int64(3798), 'spell': np.int64(4387), 'name': np.int64(2898), 'yes': np.int64(4967), 'naughty': np.int64(2918), 'make': np.int64(2585), 'wet': np.int64(4866), 'fine': np.int64(1306), 'thatåõs': np.int64(4577), 'way': np.int64(4840), 'feel': np.int64(1267), 'gota': np.int64(1612), 'england': np.int64(1075), 'macedonia': np.int64(2556), 'dont': np.int64(900), 'miss': np.int64(2748), 'news': np.int64(2964), 'ur': np.int64(4750), 'national': np.int64(2912), 'team': np.int64(4540), 'eg': np.int64(1023), 'try': np.int64(4688), 'wale': np.int64(4820), 'scotland': np.int64(4020), 'seriously': np.int64(4086), 'ha': np.int64(1694), 'pay': np.int64(3292), 'first': np.int64(1317), 'da': np.int64(656), 'stock': np.int64(4428), 'comin': np.int64(542), 'aft': np.int64(62), 'finish': np.int64(1308), 'lunch': np.int64(2536), 'str': np.int64(4437), 'lor': np.int64(2489), 'ard': np.int64(163), 'smth': np.int64(4292), 'ffffffffff': np.int64(1280), 'alright': np.int64(103), 'meet': np.int64(2673), 'sooner': np.int64(4344), 'force': np.int64(1380), 'eat': np.int64(999), 'slice': np.int64(4259), 'really': np.int64(3728), 'hungry': np.int64(1918), 'tho': np.int64(4591), 'suck': np.int64(4463), 'mark': np.int64(2617), 'worried': np.int64(4926), 'know': np.int64(2295), 'sick': np.int64(4190), 'turn': np.int64(4698), 'pizza': np.int64(3386), 'lol': np.int64(2469), 'always': np.int64(107), 'catch': np.int64(449), 'bus': np.int64(390), 'fry': np.int64(1462), 'egg': np.int64(1025), 'tea': np.int64(4537), 'mom': np.int64(2795), 'left': np.int64(2379), 'dinner': np.int64(826), 'love': np.int64(2507), 'amp': np.int64(114), 'pack': np.int64(3224), 'car': np.int64(432), 'let': np.int64(2395), 'room': np.int64(3908), 'work': np.int64(4922), 'wait': np.int64(4817), 'clear': np.int64(510), 'sure': np.int64(4492), 'sarcastic': np.int64(3983), 'yeah': np.int64(4961), 'fall': np.int64(1230), 'child': np.int64(486), 'till': np.int64(4615), 'wo': np.int64(4914), 'cheer': np.int64(479), 'tell': np.int64(4549), 'anything': np.int64(137), 'fear': np.int64(1259), 'faint': np.int64(1223), 'housework': np.int64(1887), 'quick': np.int64(3656), 'cuppa': np.int64(634), 'thanks': np.int64(4573), 'subscription': np.int64(4459), 'ringtone': np.int64(3881), 'uk': np.int64(4718), 'charge': np.int64(469), 'please': np.int64(3403), 'confirm': np.int64(560), 'yup': np.int64(4986), 'look': np.int64(2480), 'timing': np.int64(4617), 'msg': np.int64(2837), 'xuhui': np.int64(4949), 'learn': np.int64(2373), 'lesson': np.int64(2394), 'oops': np.int64(3145), 'roommate': np.int64(3910), 'do': np.int64(870), 'see': np.int64(4049), 'letter': np.int64(2396), 'decide': np.int64(705), 'hello': np.int64(1788), 'saturday': np.int64(3994), 'texting': np.int64(4567), 'tomo': np.int64(4644), 'invite': np.int64(2080), 'pls': np.int64(3411), 'ahead': np.int64(73), 'weekend': np.int64(4853), 'abiola': np.int64(10), 'forget': np.int64(1386), 'need': np.int64(2937), 'crave': np.int64(608), 'sweet': np.int64(4501), 'mmmmmm': np.int64(2770), 'yummy': np.int64(4981), 'rodger': np.int64(3899), 'burn': np.int64(389), 'sm': np.int64(4272), 'nokia': np.int64(3006), 'camcorder': np.int64(420), 'delivery': np.int64(736), 'tomorrow': np.int64(4646), 'hope': np.int64(1866), 'man': np.int64(2593), 'well': np.int64(4859), 'endowed': np.int64(1067), 'lt': np.int64(2523), 'gt': np.int64(1666), 'inch': np.int64(2001), 'hep': np.int64(1798), 'immunisation': np.int64(1986), 'nigeria': np.int64(2976), 'fair': np.int64(1224), 'hopefully': np.int64(1868), 'tyler': np.int64(4712), 'ca': np.int64(401), 'could': np.int64(593), 'maybe': np.int64(2652), 'ask': np.int64(183), 'bit': np.int64(291), 'hospital': np.int64(1876), 'keep': np.int64(2252), 'weak': np.int64(4841), 'sucker': np.int64(4464), 'saw': np.int64(3999), 'class': np.int64(506), 'gram': np.int64(1625), 'usually': np.int64(4766), 'run': np.int64(3937), 'half': np.int64(1708), 'eighth': np.int64(1029), 'smart': np.int64(4275), 'almost': np.int64(99), 'whole': np.int64(4877), 'second': np.int64(4041), 'fyi': np.int64(1489), 'ride': np.int64(3874), 'morning': np.int64(2816), 'crash': np.int64(607), 'place': np.int64(3388), 'wow': np.int64(4932), 'never': np.int64(2957), 'realize': np.int64(3726), 'embarassed': np.int64(1051), 'since': np.int64(4213), 'best': np.int64(272), 'seem': np.int64(4053), 'happy': np.int64(1733), 'sorry': np.int64(4352), 'give': np.int64(1562), 'offer': np.int64(3092), 'embarassing': np.int64(1052), 'ac': np.int64(20), 'sptv': np.int64(4403), 'new': np.int64(2961), 'jersey': np.int64(2169), 'devil': np.int64(784), 'detroit': np.int64(779), 'red': np.int64(3760), 'play': np.int64(3397), 'ice': np.int64(1947), 'hockey': np.int64(1836), 'correct': np.int64(586), 'incorrect': np.int64(2010), 'end': np.int64(1065), 'mallika': np.int64(2592), 'sherawat': np.int64(4130), 'yesterday': np.int64(4969), 'find': np.int64(1305), 'url': np.int64(4755), 'congrats': np.int64(565), 'year': np.int64(4962), 'special': np.int64(4381), 'cinema': np.int64(500), 'pas': np.int64(3274), 'suprman': np.int64(4490), 'etc': np.int64(1127), 'later': np.int64(2353), 'meeting': np.int64(2675), 'reach': np.int64(3713), 'gauti': np.int64(1514), 'sehwag': np.int64(4056), 'odi': np.int64(3087), 'series': np.int64(4084), 'pick': np.int64(3364), 'burger': np.int64(388), 'move': np.int64(2830), 'pain': np.int64(3228), 'kill': np.int64(2275), 'good': np.int64(1594), 'girl': np.int64(1557), 'situation': np.int64(4229), 'seeker': np.int64(4052), 'part': np.int64(3266), 'check': np.int64(478), 'iq': np.int64(2093), 'forever': np.int64(1383), 'come': np.int64(540), 'double': np.int64(912), 'hair': np.int64(1703), 'dresser': np.int64(939), 'wun': np.int64(4943), 'cut': np.int64(647), 'short': np.int64(4162), 'nice': np.int64(2970), 'advise': np.int64(56), 'follow': np.int64(1364), 'recent': np.int64(3744), 'review': np.int64(3862), 'mob': np.int64(2778), 'award': np.int64(210), 'bonus': np.int64(324), 'dedicated': np.int64(712), 'day': np.int64(689), 'song': np.int64(4339), 'dedicate': np.int64(711), 'valuable': np.int64(4772), 'frnds': np.int64(1449), 'rply': np.int64(3919), 'complimentary': np.int64(553), 'trip': np.int64(4680), 'eurodisinc': np.int64(1131), 'trav': np.int64(4676), 'aco': np.int64(30), 'dis': np.int64(836), 'morefrmmob': np.int64(2813), 'shracomorsglsuplt': np.int64(4176), 'hear': np.int64(1770), 'ken': np.int64(2255), 'plane': np.int64(3392), 'wah': np.int64(4814), 'lucky': np.int64(2530), 'save': np.int64(3997), 'money': np.int64(2800), 'hee': np.int64(1782), 'hi': np.int64(1809), 'babe': np.int64(215), 'im': np.int64(1976), 'wan': np.int64(4825), 'something': np.int64(4327), 'xx': np.int64(4950), 'perform': np.int64(3320), 'machan': np.int64(2558), 'thats': np.int64(4576), 'cool': np.int64(582), 'gentleman': np.int64(1532), 'dignity': np.int64(819), 'respect': np.int64(3838), 'people': np.int64(3314), 'much': np.int64(2848), 'shy': np.int64(4185), 'pa': np.int64(3222), 'operate': np.int64(3150), 'job': np.int64(2184), 'ta': np.int64(4515), 'earn': np.int64(991), 'ah': np.int64(71), 'stop': np.int64(4433), 'urgnt': np.int64(4754), 'sms': np.int64(4289), 'real': np.int64(3723), 'yo': np.int64(4974), 'ticket': np.int64(4611), 'one': np.int64(3132), 'jacket': np.int64(2128), 'multis': np.int64(2857), 'start': np.int64(4413), 'bed': np.int64(252), 'coin': np.int64(531), 'factory': np.int64(1217), 'nitros': np.int64(2992), 'ela': np.int64(1034), 'il': np.int64(1971), 'download': np.int64(919), 'wen': np.int64(4861), 'stand': np.int64(4410), 'close': np.int64(516), 'another': np.int64(127), 'night': np.int64(2978), 'spent': np.int64(4391), 'afternoon': np.int64(63), 'mean': np.int64(2659), 'include': np.int64(2004), 'sheet': np.int64(4126), 'smile': np.int64(4282), 'pleasure': np.int64(3406), 'trouble': np.int64(4681), 'pours': np.int64(3484), 'rain': np.int64(3675), 'hurt': np.int64(1924), 'becoz': np.int64(251), 'someone': np.int64(4321), 'service': np.int64(4089), 'representative': np.int64(3820), 'guaranteed': np.int64(1670), 'havent': np.int64(1752), 'planning': np.int64(3394), 'buy': np.int64(394), 'lido': np.int64(2404), 'show': np.int64(4172), 'collect': np.int64(534), 'simply': np.int64(4210), 'password': np.int64(3280), 'verify': np.int64(4780), 'usher': np.int64(4764), 'britney': np.int64(362), 'fml': np.int64(1358), 'telugu': np.int64(4552), 'movie': np.int64(2831), 'abt': np.int64(17), 'load': np.int64(2455), 'loan': np.int64(2456), 'wk': np.int64(4905), 'hols': np.int64(1848), 'hairdresser': np.int64(1705), 'appointment': np.int64(152), 'four': np.int64(1403), 'shower': np.int64(4173), 'cause': np.int64(450), 'prob': np.int64(3566), 'ham': np.int64(1713), 'nothing': np.int64(3033), 'else': np.int64(1046), 'okay': np.int64(3110), 'price': np.int64(3546), 'long': np.int64(2476), 'legal': np.int64(2382), 'ave': np.int64(205), 'drive': np.int64(942), 'test': np.int64(4563), 'yet': np.int64(4970), 'guess': np.int64(1675), 'boston': np.int64(335), 'men': np.int64(2690), 'change': np.int64(466), 'location': np.int64(2459), 'nyc': np.int64(3066), 'cuz': np.int64(652), 'signin': np.int64(4199), 'page': np.int64(3226), 'umma': np.int64(4721), 'life': np.int64(2406), 'vava': np.int64(4776), 'lot': np.int64(2495), 'dear': np.int64(697), 'wish': np.int64(4898), 'birthday': np.int64(289), 'truly': np.int64(4685), 'memorable': np.int64(2688), 'aight': np.int64(77), 'hit': np.int64(1820), 'would': np.int64(4930), 'ip': np.int64(2087), 'address': np.int64(46), 'consider': np.int64(569), 'computer': np.int64(554), 'minecraft': np.int64(2731), 'server': np.int64(4088), 'grumpy': np.int64(1663), 'old': np.int64(3122), 'lie': np.int64(2405), 'worry': np.int64(4927), 'busy': np.int64(392), 'plural': np.int64(3415), 'noun': np.int64(3039), 'research': np.int64(3825), 'cos': np.int64(588), 'thing': np.int64(4584), 'scar': np.int64(4007), 'mah': np.int64(2576), 'loud': np.int64(2502), 'gent': np.int64(1530), 'contact': np.int64(573), 'last': np.int64(2349), 'draw': np.int64(931), 'guarantee': np.int64(1669), 'wa': np.int64(4813), 'openin': np.int64(3148), 'sentence': np.int64(4078), 'formal': np.int64(1394), 'anyway': np.int64(139), 'juz': np.int64(2224), 'tt': np.int64(4692), 'eatin': np.int64(1000), 'puttin': np.int64(3641), 'weight': np.int64(4856), 'haha': np.int64(1699), 'anythin': np.int64(136), 'happen': np.int64(1727), 'enter': np.int64(1084), 'cabin': np.int64(402), 'bos': np.int64(334), 'felt': np.int64(1273), 'askd': np.int64(184), 'apartment': np.int64(144), 'specially': np.int64(4382), 'holiday': np.int64(1845), 'flight': np.int64(1339), 'inc': np.int64(2000), 'operator': np.int64(3151), 'goodo': np.int64(1602), 'must': np.int64(2872), 'friday': np.int64(1438), 'ratio': np.int64(3701), 'tortilla': np.int64(4657), 'hmm': np.int64(1830), 'uncle': np.int64(4726), 'inform': np.int64(2028), 'school': np.int64(4014), 'directly': np.int64(832), 'food': np.int64(1372), 'private': np.int64(3559), 'account': np.int64(28), 'statement': np.int64(4415), 'unredeemed': np.int64(4739), 'identifier': np.int64(1956), 'expires': np.int64(1194), 'landline': np.int64(2332), 'pair': np.int64(3232), 'malarky': np.int64(2589), 'voda': np.int64(4802), 'number': np.int64(3053), 'match': np.int64(2634), 'quote': np.int64(3664), 'standard': np.int64(4411), 'app': np.int64(147), 'sao': np.int64(3977), 'mu': np.int64(2846), 'ìï': np.int64(4999), 'predict': np.int64(3511), 'buying': np.int64(396), 'yetunde': np.int64(4971), 'bother': np.int64(336), 'sending': np.int64(4072), 'involve': np.int64(2084), 'impose': np.int64(1992), 'apologise': np.int64(146), 'del': np.int64(728), 'bak': np.int64(221), 'sum': np.int64(4473), 'lucyxx': np.int64(2533), 'answer': np.int64(130), 'sunshine': np.int64(4480), 'quiz': np.int64(3662), 'top': np.int64(4654), 'sony': np.int64(4340), 'dvd': np.int64(983), 'player': np.int64(3398), 'country': np.int64(596), 'algarve': np.int64(94), 'ansr': np.int64(129), 'sp': np.int64(4367), 'tyrone': np.int64(4714), 'lay': np.int64(2364), 'dogging': np.int64(887), 'direct': np.int64(831), 'join': np.int64(2190), 'large': np.int64(2346), 'bt': np.int64(374), 'txting': np.int64(4708), 'gravel': np.int64(1635), 'nt': np.int64(3045), 'haf': np.int64(1698), 'msn': np.int64(2840), 'yijue': np.int64(4972), 'befor': np.int64(255), 'activity': np.int64(36), 'chat': np.int64(474), 'hardcore': np.int64(1735), 'age': np.int64(67), 'yr': np.int64(4980), 'lazy': np.int64(2365), 'type': np.int64(4713), 'lect': np.int64(2376), 'pouch': np.int64(3481), 'sir': np.int64(4222), 'mail': np.int64(2579), 'swt': np.int64(4511), 'thought': np.int64(4594), 'tire': np.int64(4619), 'little': np.int64(2446), 'lovable': np.int64(2506), 'person': np.int64(3332), 'coz': np.int64(602), 'somtimes': np.int64(4336), 'occupy': np.int64(3081), 'big': np.int64(280), 'heart': np.int64(1774), 'gud': np.int64(1672), 'open': np.int64(3146), 'ya': np.int64(4954), 'dot': np.int64(911), 'whats': np.int64(4868), 'staff': np.int64(4406), 'randy': np.int64(3692), 'sexy': np.int64(4099), 'female': np.int64(1274), 'local': np.int64(2458), 'luv': np.int64(2541), 'netcollex': np.int64(2952), 'ltd': np.int64(2524), 'begin': np.int64(257), 'qatar': np.int64(3644), 'pray': np.int64(3507), 'hard': np.int64(1734), 'delete': np.int64(731), 'sindu': np.int64(4215), 'birla': np.int64(286), 'soft': np.int64(4311), 'wine': np.int64(4892), 'flow': np.int64(1349), 'nevering': np.int64(2958), 'thk': np.int64(4588), 'plaza': np.int64(3401), 'everywhere': np.int64(1151), 'dirt': np.int64(834), 'floor': np.int64(1346), 'window': np.int64(4891), 'shirt': np.int64(4143), 'sometimes': np.int64(4329), 'mouth': np.int64(2829), 'dream': np.int64(934), 'without': np.int64(4903), 'joy': np.int64(2202), 'tv': np.int64(4699), 'exist': np.int64(1182), 'hail': np.int64(1702), 'mist': np.int64(2756), 'become': np.int64(250), 'leave': np.int64(2375), 'house': np.int64(1884), 'interview': np.int64(2069), 'boy': np.int64(342), 'arrange': np.int64(174), 'safe': np.int64(3955), 'envy': np.int64(1098), 'everyone': np.int64(1145), 'parent': np.int64(3259), 'hand': np.int64(1716), 'excited': np.int64(1172), 'spend': np.int64(4389), 'frnd': np.int64(1448), 'order': np.int64(3169), 'content': np.int64(574), 'goto': np.int64(1615), 'menu': np.int64(2695), 'culture': np.int64(628), 'module': np.int64(2789), 'avoid': np.int64(207), 'missunderstding': np.int64(2754), 'wit': np.int64(4901), 'beloved': np.int64(267), 'escape': np.int64(1117), 'fancy': np.int64(1237), 'lager': np.int64(2324), 'completely': np.int64(552), 'form': np.int64(1393), 'clark': np.int64(505), 'also': np.int64(105), 'utter': np.int64(4767), 'waste': np.int64(4833), 'bank': np.int64(226), 'hmmm': np.int64(1831), 'hop': np.int64(1865), 'muz': np.int64(2878), 'discuss': np.int64(847), 'liao': np.int64(2399), 'bloody': np.int64(311), 'hell': np.int64(1786), 'cant': np.int64(428), 'believe': np.int64(261), 'mr': np.int64(2833), 'ill': np.int64(1973), 'spanish': np.int64(4373), 'bath': np.int64(234), 'carlos': np.int64(439), 'mall': np.int64(2591), 'stay': np.int64(4418), 'til': np.int64(4614), 'smoke': np.int64(4286), 'worth': np.int64(4928), 'doesnt': np.int64(881), 'log': np.int64(2463), 'maneesha': np.int64(2602), 'satisfy': np.int64(3992), 'experience': np.int64(1189), 'toll': np.int64(4640), 'lift': np.int64(2411), 'especially': np.int64(1121), 'approach': np.int64(154), 'anyways': np.int64(140), 'trust': np.int64(4686), 'guy': np.int64(1686), 'handsome': np.int64(1719), 'towards': np.int64(4665), 'net': np.int64(2951), 'mummy': np.int64(2861), 'boytoy': np.int64(345), 'awesome': np.int64(212), 'minute': np.int64(2739), 'freephone': np.int64(1427), 'xmas': np.int64(4948), 'radio': np.int64(3668), 'jus': np.int64(2220), 'bathe': np.int64(235), 'si': np.int64(4186), 'unique': np.int64(4732), 'august': np.int64(198), 'league': np.int64(2372), 'touch': np.int64(4662), 'deal': np.int64(695), 'personal': np.int64(3333), 'finally': np.int64(1302), 'complete': np.int64(551), 'course': np.int64(599), 'however': np.int64(1892), 'suggest': np.int64(4469), 'able': np.int64(12), 'or': np.int64(3163), 'every': np.int64(1141), 'settle': np.int64(4093), 'wishin': np.int64(4899), 'mrng': np.int64(2835), 'hav': np.int64(1750), 'story': np.int64(4436), 'hamster': np.int64(171

In [35]:
# Encoding the Document
Train_X_CV = vectorizer.transform(Train_X)
Test_X_CV = vectorizer.transform(Test_X)

In [36]:
print("Encoded Documents are:")
print(Train_X_CV.toarray())
print(Test_X_CV.toarray())

Encoded Documents are:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

**Naive Bayes(TFIDF)**

In [37]:
# Implementing the Multinomial Naive Bayes model
NB = naive_bayes.MultinomialNB()
NB.fit(Train_X_Tfidf,Train_Y)

MultinomialNB()

In [38]:
# Predicting the labels on validation dataset
pred_NB_tfidf = NB.predict(Test_X_Tfidf)

In [39]:

# Using accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(pred_NB_tfidf, Test_Y)*100)

Naive Bayes Accuracy Score ->  97.24880382775119

**Naive Bayes(Count Vectorizer)**

In [40]:
# Implementing the Multinomial Naive Bayes model
NB = naive_bayes.MultinomialNB()
NB.fit(Train_X_CV,Train_Y)

MultinomialNB()

In [41]:
# Predicting the labels on validation dataset
pred_NB_cv = NB.predict(Test_X_CV)

In [42]:
# Using accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(pred_NB_cv, Test_Y)*100)

Naive Bayes Accuracy Score ->  96.88995215311004

**SVM(TFIDF)**

In [43]:
#Implementing SVM and setting the parameters
SVM = svm.SVC(C = 1.0, kernel = 'linear', degree = 3, gamma = 'auto')

In [44]:
SVM.fit(Train_X_Tfidf, Train_Y)

SVC(gamma='auto', kernel='linear')

In [45]:
pred_SVM_tfidf = SVM.predict(Test_X_Tfidf)

In [52]:
print("SVM Accuracy Score -> ",accuracy_score(pred_SVM_tfidf, Test_Y)*100)

SVM Accuracy Score ->  98.08612440191388

**SVM(CountVectorizer)**

In [53]:
#Implementing SVM and setting the parameters
SVM = svm.SVC(C = 1.0, kernel = 'linear', degree = 3, gamma = 'auto')

In [54]:
SVM.fit(Train_X_CV, Train_Y)

SVC(gamma='auto', kernel='linear')

In [55]:
pred_SVM_cv = SVM.predict(Test_X_CV)

In [56]:
print("SVM Accuracy Score -> ",accuracy_score(pred_SVM_cv, Test_Y)*100)

SVM Accuracy Score ->  97.96650717703349